// require("dotenv").config();
// const { query } = require("./db");

// const SCHEMA = process.env.HANA_SCHEMA || "APP"; // fallback if not set

// async function runMigrations() {
//   try {
//     console.log(`🚀 Running migrations for schema: ${SCHEMA}`);

//     // 1️⃣ Independent tables
//     await query(`
//       CREATE COLUMN TABLE "${SCHEMA}"."DOC_TYPES" (
//         "DOC_TYPE_ID" NVARCHAR(50),
//         "DOC_TYPE_NAME" NVARCHAR(100) NOT NULL,
//         "DESCRIPTION" NVARCHAR(255),
//         PRIMARY KEY ("DOC_TYPE_ID")
//       ) UNLOAD PRIORITY 5 AUTO MERGE
//     `);

//     await query(`
//       CREATE COLUMN TABLE "${SCHEMA}"."WORKFLOW_TEMPLATE" (
//         "WORKFLOW_ID" NVARCHAR(36),
//         "DOC_TYPE_ID" NVARCHAR(50),
//         "WORKFLOW_NAME" NVARCHAR(100) NOT NULL,
//         "IS_ACTIVE" BOOLEAN CS_INT DEFAULT TRUE,
//         "ALLOWED_CREATORS" NVARCHAR(1000),
//         PRIMARY KEY ("WORKFLOW_ID")
//       ) UNLOAD PRIORITY 5 AUTO MERGE
//     `);

//     await query(`
//       CREATE COLUMN TABLE "${SCHEMA}"."WORKFLOW_STEPS" (
//         "STEP_ID" NVARCHAR(50),
//         "WORKFLOW_ID" NVARCHAR(50),
//         "STEP_ORDER" INTEGER CS_INT NOT NULL,
//         "STEP_CONDITION" NVARCHAR(1000),
//         "ACTION_TYPE" NVARCHAR(20) DEFAULT 'approve',
//         "ROLE_NAMES" NVARCHAR(1000),
//         "NO_OF_APPROVAL" INTEGER CS_INT,
//         "NO_OF_REJECTION" INTEGER CS_INT,
//         PRIMARY KEY ("STEP_ID")
//       ) UNLOAD PRIORITY 5 AUTO MERGE
//     `);

//     await query(`
//       CREATE COLUMN TABLE "${SCHEMA}"."ROLES" (
//         "ID" INTEGER CS_INT GENERATED BY DEFAULT AS IDENTITY,
//         "NAME" NVARCHAR(100) NOT NULL,
//         "DESCRIPTION" NVARCHAR(255),
//         PRIMARY KEY ("ID"),
//         UNIQUE CPBTREE ("NAME")
//       ) UNLOAD PRIORITY 5 AUTO MERGE
//     `);

//     // 2️⃣ Dependent tables
//     await query(`
//       CREATE COLUMN TABLE "${SCHEMA}"."DOCUMENTS" (
//         "DOC_ID" NVARCHAR(50),
//         "DOC_TYPE_ID" NVARCHAR(50) NOT NULL,
//         "DOC_NUMBER" NVARCHAR(50),
//         "DOC_DATE" DATE CS_DAYDATE,
//         "STATUS" NVARCHAR(20) DEFAULT 'pending',
//         "WORKFLOW_ID" NVARCHAR(50),
//         "CURRENT_STEP_ID" NVARCHAR(50),
//         "PAYLOAD" CLOB MEMORY THRESHOLD 1000,
//         "CREATED_BY" NVARCHAR(100),
//         "SAP_INV_QRE_DOC_NUM" VARCHAR(50),
//         "SAP_DOC_ISSUE_DOC_NUM" VARCHAR(50),
//         "IS_POSTED_TO_SAP" BOOLEAN CS_INT DEFAULT FALSE,
//         PRIMARY KEY ("DOC_ID")
//       ) UNLOAD PRIORITY 5 AUTO MERGE
//     `);

//     await query(`
//       CREATE COLUMN TABLE "${SCHEMA}"."APPROVALS" (
//         "APPROVAL_ID" NVARCHAR(50),
//         "DOC_ID" NVARCHAR(50) NOT NULL,
//         "STEP_ID" NVARCHAR(50) NOT NULL,
//         "APPROVER_USER_ID" NVARCHAR(50) NOT NULL,
//         "APPROVAL_STATUS" NVARCHAR(20) NOT NULL,
//         "COMMENTS" NVARCHAR(1000),
//         "TIMESTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP,
//         PRIMARY KEY ("APPROVAL_ID")
//       ) UNLOAD PRIORITY 5 AUTO MERGE
//     `);

//     await query(`
//       CREATE COLUMN TABLE "${SCHEMA}"."ROLEPERMISSIONS" (
//         "ROLEID" INTEGER CS_INT NOT NULL,
//         "PERMISSION" NVARCHAR(100) NOT NULL,
//         PRIMARY KEY ("ROLEID","PERMISSION")
//       ) UNLOAD PRIORITY 5 AUTO MERGE
//     `);

//     // 3️⃣ Foreign keys
//     await query(`
//       ALTER TABLE "${SCHEMA}"."APPROVALS"
//       ADD FOREIGN KEY ("DOC_ID") REFERENCES "${SCHEMA}"."DOCUMENTS" ("DOC_ID")
//     `);

//     await query(`
//       ALTER TABLE "${SCHEMA}"."APPROVALS"
//       ADD FOREIGN KEY ("STEP_ID") REFERENCES "${SCHEMA}"."WORKFLOW_STEPS" ("STEP_ID")
//     `);

//     await query(`
//       ALTER TABLE "${SCHEMA}"."DOCUMENTS"
//       ADD FOREIGN KEY ("CURRENT_STEP_ID") REFERENCES "${SCHEMA}"."WORKFLOW_STEPS" ("STEP_ID")
//     `);

//     await query(`
//       ALTER TABLE "${SCHEMA}"."DOCUMENTS"
//       ADD CONSTRAINT "FK_DOCUMENTS_WORKFLOW_ID"
//       FOREIGN KEY ("WORKFLOW_ID") REFERENCES "${SCHEMA}"."WORKFLOW_TEMPLATE" ("WORKFLOW_ID")
//     `);

//     await query(`
//       ALTER TABLE "${SCHEMA}"."ROLEPERMISSIONS"
//       ADD FOREIGN KEY ("ROLEID") REFERENCES "${SCHEMA}"."ROLES" ("ID")
//     `);

//     console.log("✅ Migrations complete!");
//   } catch (err) {
//     console.error("❌ Migration error:", err.message);
//   }
// }

// runMigrations();
